config/routes.rb
Rails.application.routes.draw do
  get 'proyects/index'
  get 'proyects/new'
  post 'proyects/create'
  root 'proyects#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyect.rb
class Proyect < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :index
  
  def index

    if params[:search]
      @proyects = Proyect.where(status: params[:search])
    else
      @proyects = Proyect.all
    end

  end

  def new
    @proyect = Proyect.new
    
  end

  
  def create
    # Proyect.create(name: params[:name], description: params[:description], start_date: params[:start_date], finish_date: params[:finish_date], status: params[:status])
    puts params
    params[:proyect][:name]
    @proyect = Proyect.new(name: params[:proyect][:name], description: params[:proyect][:description], start_date: params[:proyect][:start_date], 
      finish_date: params[:proyect][:finish_date], status: params[:proyect][:status])

    if @proyect.save
      flash[:notice] = "Proyecto creado existosamente"
      redirect_to proyects_new_path
    else
      flash[:error] = "Ocurrió un error. Verifica que los campos Nombre y Descripción estén completados."
      redirect_to proyects_new_path
      

    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/proyects/index">Gestor de Proyectos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/proyects/index">Dashboard<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/proyects/new">Crear Proyecto<span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |type, msg| %>
        <div class= "alert alert-info">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/proyects/create.html.erb
<h1>Proyects#create</h1>
<p>Find me in app/views/proyects/create.html.erb</p>

app/views/proyects/index.html.erb
<h1>Dashboard</h1>

<%= form_tag proyects_index_path, method: :get, class: "form-inline my-2 my-lg-0 d-flex justify-content-end" do %>
  
  <div class="nav " id="search">
    <%= select_tag(:search, options_for_select(['Agendado', 'En progreso', 'Terminado']), {class: "form-control mr-sm-2"})%>
    <%= submit_tag 'Filtrar', class:"btn btn-success my-2 my-sm-0"%>
  </div>

<% end %>

<table class = "table-dark table">
  <thead>
    <tr>
      <th scope = "col">Nombre</th>
      <th scope = "col">Descripción</th>
      <th scope = "col">Fecha de inicio</th>
      <th scope = "col">Fecha de término</th>
      <th scope = "col">Estado</th>
    </tr>
  </thead>
  <tbody>
		<% @proyects.each do |proyect| %>
			<tr>
				<td><%= proyect.name %></td>
				<td><%= proyect.description %></td>
        <td><%= proyect.start_date %></td>
        <td><%= proyect.finish_date %></td>
        <td><%= proyect.status %></td>
			<tr>
		<% end %>
  </tbody>
</table>

app/views/proyects/new.html.erb
<h1>Crear Proyecto</h1>
  

<%= form_with model: @proyect, url: proyects_create_path do |f| %>

  
  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Descripción" %>
    <%= f.text_area :description, class:"form-control", rows:"3" %>
  </div>

  <div class="form-group">
    <%= f.label :start_date, "Fecha de inicio" %>
    <%= f.date_field :start_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :finish_date, "Fecha de término" %>
    <%= f.date_field :finish_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status, "Estado" %>
    <%= f.select :status, options_for_select(['Agendado', 'En progreso', 'Terminado']), {}, class: 'form-control', placeholder:"Propuesta" %>
  </div>

	<%= f.submit 'Guardar', class:"btn btn-success" %>

<% end %>

<%# f.select( :user_id,    options_from_collection_for_select(@users, :id, :name, (@user.id.nil?) ? nil : @users.id), { :include_blank => true },  {:class => 'span4'})  %>